name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: mkdir build
      - run: (cd build && git clone https://github.com/iden3/circom.git)
      - run: (cd build/circom && cargo build --release)
      - run: (cd build/circom && cargo install --path circom)
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm run info
