name: Tests
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    - run: npx hardhat test
      env:
        CI: false
